/** Real job photographs from the shop. Do not replace these with generated images. */
export const projects = [
  {
    src: "portfolio/home-theater-accent-wall.jpg",
    w: 1800,
    h: 1350,
    cat: "theater",
    catLabel: "Home theater",
    title: "Accent wall, screen, and built-in booth",
    alt: "Dark home theater with a projection screen, soundbar, and a console styled like a classic red British telephone booth.",
  },
  {
    src: "portfolio/home-theater-tv-inwall.jpg",
    w: 1800,
    h: 1350,
    cat: "theater",
    catLabel: "Home theater",
    title: "Display set into a finished wall",
    alt: "Flat-screen television recessed into a white wall above a dark wood console.",
  },
  {
    src: "portfolio/home-theater-screen-bar.jpg",
    w: 1800,
    h: 1350,
    cat: "theater",
    catLabel: "Home theater",
    title: "Screen, soundbar, and a flush outlet",
    alt: "Projection screen centered on a dark wall with a soundbar beneath it and an electrical outlet low on the wall.",
  },
  {
    src: "portfolio/home-theater-sofa.jpg",
    w: 1350,
    h: 1800,
    cat: "theater",
    catLabel: "Home theater",
    title: "Seating aimed at the screen wall",
    alt: "Dark leather sofa with two red throw pillows facing a home theater screen.",
  },
  {
    src: "portfolio/home-theater-denon-rack.jpg",
    w: 1350,
    h: 1800,
    cat: "theater",
    catLabel: "Home theater",
    title: "Receiver rack: Denon, Apple TV, shades",
    alt: "Open shelf holding a Denon receiver, an Apple TV, and a wireless remote for motorized shades.",
  },
  {
    src: "portfolio/unifi-navepoint-udm-switch.jpg",
    w: 1350,
    h: 1800,
    cat: "unifi",
    catLabel: "UniFi / security",
    title: "Dream Machine and switch, labeled",
    alt: "NavePoint wall cabinet with a UniFi Dream Machine, a UniFi switch, and labeled Ethernet patch cables.",
  },
  {
    src: "portfolio/unifi-navepoint-side.jpg",
    w: 1350,
    h: 1800,
    cat: "unifi",
    catLabel: "UniFi / security",
    title: "Cabinet side, gear in order",
    alt: "Side view of an open NavePoint network cabinet with the door swung wide and equipment stacked inside.",
  },
  {
    src: "portfolio/security-cam-1.jpg",
    w: 1350,
    h: 1800,
    cat: "unifi",
    catLabel: "UniFi / security",
    title: "Turret camera under the eave",
    alt: "White UniFi turret camera mounted under a beige eave beside a black downspout.",
  },
  {
    src: "portfolio/security-cam-2.jpg",
    w: 1800,
    h: 1350,
    cat: "unifi",
    catLabel: "UniFi / security",
    title: "Turret aimed along the walk",
    alt: "White dome security camera under a vinyl soffit, aimed down a concrete walkway.",
  },
  {
    src: "portfolio/security-cam-3.jpg",
    w: 1350,
    h: 1800,
    cat: "unifi",
    catLabel: "UniFi / security",
    title: "Camera at the stone corner",
    alt: "White turret security camera mounted where a downspout meets a stacked-stone corner pier.",
  },
  {
    src: "portfolio/security-cam-4.jpg",
    w: 1350,
    h: 1800,
    cat: "unifi",
    catLabel: "UniFi / security",
    title: "Second camera by the entry",
    alt: "White turret security camera beside a black downspout, aimed toward a glass entry door.",
  },
  {
    src: "portfolio/data-rack-black-wallmount.jpg",
    w: 1350,
    h: 1800,
    cat: "racks",
    catLabel: "Data racks",
    title: "Wall-mount rack, patch panel, and UPS",
    alt: "Black wall-mount network cabinet with a patch panel, switch, power strip, and a CyberPower UPS.",
  },
  {
    src: "portfolio/electrical-6.jpg",
    w: 1800,
    h: 1350,
    cat: "electrical",
    catLabel: "Electrical",
    title: "Deadfront on, directory started",
    alt: "Closed residential breaker panel with a handwritten circuit directory on the inside of the door.",
  },
  {
    src: "portfolio/electrical-1.jpg",
    w: 1800,
    h: 1350,
    cat: "electrical",
    catLabel: "Electrical",
    title: "Breakers seated in the panel",
    alt: "Residential electrical panel interior with rows of branch circuit breakers.",
  },
  {
    src: "portfolio/electrical-3.jpg",
    w: 1350,
    h: 1800,
    cat: "electrical",
    catLabel: "Electrical",
    title: "Main at the top, branches below",
    alt: "Open electrical panel with a large main breaker above two columns of branch breakers.",
  },
  {
    src: "portfolio/electrical-2.jpg",
    w: 1350,
    h: 1800,
    cat: "electrical",
    catLabel: "Electrical",
    title: "Branch breakers, labeled",
    alt: "Close view of labeled branch breakers inside a residential panel.",
  },
  {
    src: "portfolio/electrical-5.jpg",
    w: 1350,
    h: 1800,
    cat: "electrical",
    catLabel: "Electrical",
    title: "Marked before the cover goes on",
    alt: "Electrical panel with handwritten labels on the breakers before the deadfront is finished.",
  },
  {
    src: "portfolio/electrical-4.jpg",
    w: 1350,
    h: 1800,
    cat: "electrical",
    catLabel: "Electrical",
    title: "Panel interior during makeup",
    alt: "Partly populated residential panel with white and black conductors landing on the breakers.",
  },
]
